

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env  # <-- Add this line
    networks:
      - app-network

  frontend:
    # ... frontend configuration remains the same
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.template
    networks:
      - app-network

networks:
  app-network:
    driver: bridge