

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend_dev
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=key # Replace with your actual Gemini API key
    volumes:
      - ./backend/app:/app/app
    networks:
      - app-network

  frontend:
    # ... frontend configuration remains the same
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge